//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager.Data
{
    using System;
    using System.Collections.Generic;

    public partial class PlayList
    {
        public PlayList()
        {
            this.PlayListArtists = new HashSet<PlayListArtist>();
            this.PlayListGenres = new HashSet<PlayListGenre>();
            this.SearchCritrias = new HashSet<SearchCritria>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public int UserId { get; set; }

        public virtual ICollection<PlayListArtist> PlayListArtists { get; set; }
        public virtual ICollection<PlayListGenre> PlayListGenres { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<SearchCritria> SearchCritrias { get; set; }
    }
}
