//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager.Data
{
    using System;
    using System.Collections.Generic;

    public partial class Property
    {
        public Property()
        {
            this.PropertyOptions = new HashSet<PropertyOption>();
            this.SearchCritrias = new HashSet<SearchCritria>();
            this.TrackProperties = new HashSet<TrackProperty>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int PropertyTypeId { get; set; }
        public bool SearchCriteriaOnly { get; set; }

        public virtual PropertyType PropertyType { get; set; }
        public virtual ICollection<PropertyOption> PropertyOptions { get; set; }
        public virtual ICollection<SearchCritria> SearchCritrias { get; set; }
        public virtual ICollection<TrackProperty> TrackProperties { get; set; }
    }
}
