//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager.Data
{
    using System;
    using System.Collections.Generic;

    public partial class PropertyOption
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public int PropertyId { get; set; }
        public int Sequence { get; set; }

        public virtual Property Property { get; set; }
    }
}
