//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager.Data
{
    using System;
    using System.Collections.Generic;

    public partial class Track
    {
        public Track()
        {
            this.MusicVideos = new HashSet<MusicVideo>();
            this.MusicVideos1 = new HashSet<MusicVideo>();
            this.TrackProperties = new HashSet<TrackProperty>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int AlbumID { get; set; }
        public string FilePath { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> TrackNr { get; set; }

        public virtual Album Album { get; set; }
        public virtual ICollection<MusicVideo> MusicVideos { get; set; }
        public virtual ICollection<MusicVideo> MusicVideos1 { get; set; }
        public virtual ICollection<TrackProperty> TrackProperties { get; set; }
    }
}
